// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Context() {
  return window['go']['gui']['App']['Context']();
}

export function GetProcessDetails(arg1) {
  return window['go']['gui']['App']['GetProcessDetails'](arg1);
}

export function GetSystemAnalytics() {
  return window['go']['gui']['App']['GetSystemAnalytics']();
}

export function ListRunningProcesses() {
  return window['go']['gui']['App']['ListRunningProcesses']();
}

export function MinimizeToTray() {
  return window['go']['gui']['App']['MinimizeToTray']();
}

export function QuitApp() {
  return window['go']['gui']['App']['QuitApp']();
}

export function Search(arg1, arg2, arg3) {
  return window['go']['gui']['App']['Search'](arg1, arg2, arg3);
}
