// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {gui} from '../models';

export function Context():Promise<context.Context>;

export function GetProcessDetails(arg1:number):Promise<gui.GUIResult>;

export function GetSystemAnalytics():Promise<gui.SystemAnalytics>;

export function ListRunningProcesses():Promise<Array<gui.GUIProcessItem>>;

export function MinimizeToTray():Promise<void>;

export function QuitApp():Promise<void>;

export function Search(arg1:string,arg2:string,arg3:boolean):Promise<gui.GUIResult>;
