package completion

// Bash returns the bash completion script for witr.
func Bash() string {
	return `# witr bash completion
# Generated by: witr completion bash

_witr_completions() {
    local cur prev opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    # Handle completion subcommand
    if [[ "${COMP_WORDS[1]}" == "completion" ]]; then
        if [[ ${COMP_CWORD} -eq 2 ]]; then
            COMPREPLY=($(compgen -W "bash zsh fish" -- "${cur}"))
        fi
        return 0
    fi

    # Don't complete after --help or --version
    local word
    for word in "${COMP_WORDS[@]}"; do
        case "$word" in
            --help|--version)
                return 0
                ;;
        esac
    done

    # Check if we already have a target
    local has_target=0
    for word in "${COMP_WORDS[@]}"; do
        case "$word" in
            --pid|--port)
                has_target=1
                ;;
        esac
    done

    # Handle flag arguments
    case "${prev}" in
        --pid|-pid)
            COMPREPLY=($(compgen -W "$(witr __complete pids 2>/dev/null)" -- "${cur}"))
            return 0
            ;;
        --port|-port)
            COMPREPLY=($(compgen -W "$(witr __complete ports 2>/dev/null)" -- "${cur}"))
            return 0
            ;;
    esac

    # Handle flag completion
    if [[ "${cur}" == -* ]]; then
        opts="--pid --port --short --tree --json --warnings --no-color --env --help --version"
        COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
        return 0
    fi

    # Don't offer process names if we already have a target
    if [[ ${has_target} -eq 1 ]]; then
        return 0
    fi

    # First argument: offer 'completion' subcommand and process names
    if [[ ${COMP_CWORD} -eq 1 ]]; then
        COMPREPLY=($(compgen -W "completion $(witr __complete processes 2>/dev/null)" -- "${cur}"))
    else
        # Subsequent arguments: only process names
        COMPREPLY=($(compgen -W "$(witr __complete processes 2>/dev/null)" -- "${cur}"))
    fi
}

complete -F _witr_completions witr
`
}
