package completion

// Fish returns the fish shell completion script for witr.
func Fish() string {
	return `# witr fish completion
# Generated by: witr completion fish

# Disable file completions for the entire command
complete -c witr -f

# Subcommand: completion (not after --help or --version)
complete -c witr -n "__fish_use_subcommand; and __witr_no_terminal_flag" -a "completion" -d "Generate shell completion scripts"

# Completion subcommand shells
complete -c witr -n "__fish_seen_subcommand_from completion" -a "bash" -d "Generate bash completion script"
complete -c witr -n "__fish_seen_subcommand_from completion" -a "zsh" -d "Generate zsh completion script"
complete -c witr -n "__fish_seen_subcommand_from completion" -a "fish" -d "Generate fish completion script"
complete -c witr -n "__fish_seen_subcommand_from completion" -a "powershell" -d "Generate PowerShell completion script"
complete -c witr -n "__fish_seen_subcommand_from completion" -a "pwsh" -d "Generate PowerShell (Core) completion script"

# Helper to check if --help or --version was given
function __witr_no_terminal_flag
    not __fish_contains_opt help version
end

# Helper to check if we already have a target
function __witr_needs_target
    not __fish_contains_opt pid port; and test (count (string match -rv '^-' -- (commandline -opc)[2..-1])) -eq 0
end

# Flags (only when not in completion subcommand and no terminal flags)
complete -c witr -n "not __fish_seen_subcommand_from completion; and __witr_no_terminal_flag" -l pid -d "Explain a specific PID" -x -a "(__witr_complete_pids)"
complete -c witr -n "not __fish_seen_subcommand_from completion; and __witr_no_terminal_flag; and not __fish_contains_opt pid" -l port -d "Explain port usage" -x -a "(__witr_complete_ports)"
complete -c witr -n "not __fish_seen_subcommand_from completion; and __witr_no_terminal_flag" -l short -d "One-line summary"
complete -c witr -n "not __fish_seen_subcommand_from completion; and __witr_no_terminal_flag" -l tree -d "Show full process ancestry tree"
complete -c witr -n "not __fish_seen_subcommand_from completion; and __witr_no_terminal_flag" -l json -d "Output result as JSON"
complete -c witr -n "not __fish_seen_subcommand_from completion; and __witr_no_terminal_flag" -l warnings -d "Show only warnings"
complete -c witr -n "not __fish_seen_subcommand_from completion; and __witr_no_terminal_flag" -l no-color -d "Disable colorized output"
complete -c witr -n "not __fish_seen_subcommand_from completion; and __witr_no_terminal_flag" -l env -d "Show only environment variables"
complete -c witr -n "not __fish_seen_subcommand_from completion" -l help -d "Show help message"
complete -c witr -n "not __fish_seen_subcommand_from completion" -l version -d "Show version and exit"

# Process name completion for positional argument (only if no target yet and no terminal flags)
complete -c witr -n "not __fish_seen_subcommand_from completion; and __witr_no_terminal_flag; and __witr_needs_target" -a "(__witr_complete_processes)"

# Helper function for PID completion
function __witr_complete_pids
    witr __complete pids 2>/dev/null
end

# Helper function for port completion
function __witr_complete_ports
    witr __complete ports 2>/dev/null
end

# Helper function for process name completion
function __witr_complete_processes
    witr __complete processes 2>/dev/null
end
`
}
