package completion

// Zsh returns the zsh completion script for witr.
func Zsh() string {
	return `#compdef witr
# witr zsh completion
# Generated by: witr completion zsh

_witr() {
    local curcontext="$curcontext" state line
    typeset -A opt_args

    # Handle completion subcommand
    if [[ ${words[2]} == "completion" ]]; then
        if (( CURRENT == 3 )); then
            local -a shells
            shells=(bash zsh fish powershell pwsh)
            _describe -t shells 'shell' shells
        fi
        return
    fi

    # Don't complete after --help or --version
    if [[ ${words[(I)--help]} -gt 0 ]] || [[ ${words[(I)--version]} -gt 0 ]]; then
        return
    fi

    # Check if we already have a target (--pid, --port, or positional process name)
    local has_target=0
    if [[ ${words[(I)--pid]} -gt 0 ]] || [[ ${words[(I)--port]} -gt 0 ]]; then
        has_target=1
    fi
    # Check for positional argument (non-flag, non-completion)
    for word in ${words[2,-1]}; do
        if [[ $word != -* ]] && [[ $word != "completion" ]]; then
            has_target=1
            break
        fi
    done

    # If completing first non-flag argument, offer completion subcommand and processes
    if (( CURRENT == 2 )) && [[ ${words[2]} != -* ]]; then
        _alternative \
            'commands:command:compadd completion' \
            'processes:process name:_witr_processes'
        return
    fi

    _arguments -s \
        '(--port)--pid[Explain a specific PID]:pid:_witr_pids' \
        '(--pid)--port[Explain port usage]:port:_witr_ports' \
        '--short[One-line summary]' \
        '--tree[Show full process ancestry tree]' \
        '--json[Output result as JSON]' \
        '--warnings[Show only warnings]' \
        '--no-color[Disable colorized output]' \
        '--env[Show only environment variables]' \
        '(*)--help[Show help message]' \
        '(*)--version[Show version and exit]'
}

# Complete with running PIDs
_witr_pids() {
    local -a pids
    pids=(${(f)"$(witr __complete pids 2>/dev/null)"})
    _describe -t pids 'process ID' pids
}

# Complete with listening ports
_witr_ports() {
    local -a ports
    ports=(${(f)"$(witr __complete ports 2>/dev/null)"})
    _describe -t ports 'listening port' ports
}

# Complete with running process names
_witr_processes() {
    local -a procs
    procs=(${(f)"$(witr __complete processes 2>/dev/null)"})
    _describe -t processes 'process name' procs
}

compdef _witr witr
`
}
